apiVersion: v1
kind: Pod
metadata:
  name: inspectnode164121
  labels:
    name: inspectnode
  namespace: kube-system
spec:
  tolerations:
    - operator: "Exists"
  hostNetwork: true
  containers:
    - name: inspectnode164121
      image: nkkashyap/inspectndoe:v001
      volumeMounts:
      - mountPath: /host/root
        name: host-root
      - mountPath: /host/etc
        name: host-etc
      - mountPath: /host/log
        name: host-log
      - mountPath: /host/local
        name: host-local
      - mountPath: /run/systemd
        name: host-systemd

  volumes:
  - name: host-root
    hostPath:
      path: /root/
  - name: host-etc
    hostPath:
      path: /etc
  - name: host-log
    hostPath:
      path: /var/log
  - name: host-local
    hostPath:
      path: /usr/local
  - name: host-systemd
    hostPath:
      path: /run/systemd

  nodeSelector:
    kubernetes.io/hostname: 10.76.215.177